AWSTemplateFormatVersion: "2010-09-09"

Resources:
  EC2Role:
    Type: AWS::IAM::Role
    Properties:
      RoleName: laravel-ec2-role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole

  InstancePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: laravel-ec2-policy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Resource: "*"
            Action:
              - s3:*
              - sqs:*
      Roles:
        - !Ref EC2Role

  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: laravel-instance-profile
      Roles:
        - !Ref EC2Role

  LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: laravel-launch-template
      LaunchTemplateData:
        KeyName: applaravel 
        IamInstanceProfile:
          Name: !Ref InstanceProfile
        ImageId: ami-053b0d53c279acc90
        InstanceType: t2.micro
        SecurityGroupIds:
          - !ImportValue laravel-vpc-EC2SecurityGroup

  EC2Instance1:
    Type: AWS::EC2::Instance
    Properties:
      SubnetId: !ImportValue laravel-vpc-PublicSubnetOne
      LaunchTemplate:
        LaunchTemplateId: !Ref LaunchTemplate
        Version: !GetAtt LaunchTemplate.LatestVersionNumber
      Tags:
        - Key: Name
          Value: laravel-instance-1

  EC2Instance2:
    Type: AWS::EC2::Instance
    Properties:
      SubnetId: !ImportValue laravel-vpc-PublicSubnetTwo
      LaunchTemplate:
        LaunchTemplateId: !Ref LaunchTemplate
        Version: !GetAtt LaunchTemplate.LatestVersionNumber
      Tags:
        - Key: Name
          Value: laravel-instance-2



